const PAID_TO_CONTACT_OPTIONS_DOT_CONTACT_OPTIONS = [
  {
    id: "22",
    displayId: "",
    displayName: "a a",
    contactType: "Customer",
    displayContactType: "Customer",
  },
  {
    id: "20",
    displayId: "",
    displayName: "A B",
    contactType: "Customer",
    displayContactType: "Customer",
  },
  {
    id: "5",
    displayId: "",
    displayName: "asdf asdf",
    contactType: "Customer",
    displayContactType: "Customer",
  },
  {
    id: "1",
    displayId: "",
    displayName: "Company A",
    contactType: "Customer",
    displayContactType: "Customer",
  },
  {
    id: "21",
    displayId: "",
    displayName: "f f",
    contactType: "Customer",
    displayContactType: "Customer",
  },
  {
    id: "10",
    displayId: "",
    displayName: "Individual Customer",
    contactType: "Customer",
    displayContactType: "Customer",
  },
  {
    id: "15",
    displayId: "",
    displayName: "Individual Personal",
    contactType: "Other",
    displayContactType: "Personal",
  },
  {
    id: "14",
    displayId: "",
    displayName: "Individual Supplier",
    contactType: "Supplier",
    displayContactType: "Supplier",
  },
  {
    id: "9",
    displayId: "",
    displayName: "Supplier  One",
    contactType: "Supplier",
    displayContactType: "Supplier",
  },
  {
    id: "23",
    displayId: "",
    displayName: "z z",
    contactType: "Customer",
    displayContactType: "Customer",
  },
  {
    id: "23",
    displayId: "",
    displayName: "z z",
    contactType: "Customer",
    displayContactType: "Customer",
  },
];
