const MENU_ARR = [
  {
    title: "Admin Tools",
    link: "/#",
    component: "",
    data: "",
    icon: "fas fa-users-cog",
    Subitems: [
      {
        title: "Staff Portal",
        link: "/#",
        component: "",
        data: "",
        icon: "fas fa-sim-card",
        Subitems: [
          {
            title: "Menu",
            link: "/menu",
            component: "Menu",
            data: "",
            icon: "fas fa-bars",
          },
          {
            title: "Roles",
            link: "/roles",
            component: "Roles",
            data: "",
            icon: "fas fa-users-cog",
          },
          {
            title: "Permissions",
            link: "/permissions",
            component: "Permissions",
            data: "",
            icon: "fas fa-user-lock",
          },
          {
            title: "Users",
            link: "/users",
            component: "Users",
            data: "",
            icon: "fas fa-users",
          },
        ],
      },
      {
        title: "Rsp Portal",
        link: "/#",
        component: "",
        data: "",
        icon: "far fa-registered",
        Subitems: [
          {
            title: "Users",
            link: "/rsp/users",
            component: "RspUsers",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Roles",
            link: "/rsp/roles",
            component: "RspRoles",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Menu",
            link: "/rsp/menu",
            component: "RspMenu",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Config",
            link: "/rsp/config",
            component: "RspConfig",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Permissions",
            link: "/rsp/permissions",
            component: "RspPermissions",
            data: "",
            icon: "fas fa-font",
          },
        ],
      },
      {
        title: "Flows",
        link: "/flow#",
        component: "",
        data: "",
        icon: "fas fa-tasks",
        Subitems: [
          {
            title: "Flow",
            link: "/flows",
            component: "Flows",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Tasks",
            link: "/tasks",
            component: "Tasks",
            data: "",
            icon: "fas fa-font",
          },
        ],
      },
      {
        title: "Other Reports",
        link: "/#",
        component: "",
        data: "",
        icon: "fas fa-font",
        Subitems: [
          {
            title: "SQL",
            link: "/sql",
            component: "Sql",
            data: "",
            icon: "fas fa-database",
          },
          {
            title: "Custom",
            link: "/custom",
            component: "CustomReports",
            data: "",
            icon: "fas fa-table",
          },
        ],
      },
    ],
  },
  {
    title: "Dev Requests",
    link: "/dev-requests/:task?",
    component: "DevRequests",
    data: "",
    icon: "fas fa-code",
  },
  {
    title: "Reports",
    link: "/#",
    component: "",
    data: "",
    icon: "fas fa-clipboard",
    Subitems: [
      {
        title: "Sync Reports",
        link: "/#",
        component: "",
        data: "",
        icon: "fas fa-sync",
        Subitems: [
          {
            title: "Properties",
            link: "/sync/OptiComm_DADPropertyLogs",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "ONTS",
            link: "/sync/OptiComm_DADOntLogs",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
        ],
      },
      {
        title: "Data Extracts",
        link: "/#",
        component: "",
        data: "",
        icon: "fas fa-gopuram",
        Subitems: [
          {
            title: "Dashboard Reports",
            link: "/#",
            component: "",
            data: "",
            icon: "fas fa-font",
            Subitems: [
              {
                title: "Active Premesis",
                link: "/dashboard/Dashboard_Active",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Connected Premises",
                link: "/dashboard/Dashboard_Connected",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Passed Premises",
                link: "/dashboard/Dashboard_Passed",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
            ],
          },
          {
            title: "Crystal Reports",
            link: "/#",
            component: "",
            data: "",
            icon: "fas fa-book-dead",
            Subitems: [
              {
                title: "Joomla All Properties",
                link: "/crystal/Joomla_Properties",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Joomla Active Services",
                link: "/crystal/Joomla_Active",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Joomla All Services",
                link: "/crystal/Joomla_All",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Joomla ONTs",
                link: "/crystal/Joomla_ONTs",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Joomla Communites",
                link: "/crystal/Joomla_Communities",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Joomla Products",
                link: "/crystal/Joomla_Products",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Joomla RSPs",
                link: "/crystal/Joomla_RSPs",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Joomla - RSP Charges",
                link: "/crystal/Joomla_Charges",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
            ],
          },
          {
            title: "DataWarehouse Reports",
            link: "/#",
            component: "",
            data: "",
            icon: "fas fa-file-contract",
            Subitems: [
              {
                title: "Exchanges",
                link: "/dw/DW_Exchanges",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Communities",
                link: "/dw/DW_Communities",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "ONTs",
                link: "/dw/DW_ONTs",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Properties",
                link: "/dw/DW_Properties",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Active Services",
                link: "/dw/DW_ActiveServices",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "All Services",
                link: "/dw/DW_AllServices",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Products",
                link: "/dw/DW_Products",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "OLTs",
                link: "/dw/DW_OLTs",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
            ],
          },
        ],
      },
      {
        title: "Network Reports",
        link: "/#",
        component: "",
        data: "",
        icon: "fas fa-chalkboard",
        Subitems: [
          {
            title: "LBNco Entitlements",
            link: "/network/Lbnco_Entitlement",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Site Limits",
            link: "/#",
            component: "",
            data: "",
            icon: "fas fa-font",
            Subitems: [
              {
                title: "OptiComm",
                link: "/network/Site_Restrictions",
                component: "CustomReports",
                data: "",
                icon: "fas fa-memory",
              },
              {
                title: "LBNco",
                link: "/network/Lbnco_SiteLimits",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
            ],
          },
          {
            title: "Site Uptake",
            link: "/#",
            component: "",
            data: "",
            icon: "fas fa-font",
            Subitems: [
              {
                title: "LBNco",
                link: "/network/Lbnco_Sites",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "OptiComm",
                link: "/network/Opticomm_Sites",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
            ],
          },
        ],
      },
      {
        title: "Service Reports",
        link: "/#",
        component: "",
        data: "",
        icon: "fas fa-balance-scale",
        Subitems: [
          {
            title: "LBNco Services",
            link: "/network/Lbnco_Services",
            component: "CustomReports",
            data: "",
            icon: "fas fa-code-branch",
          },
          {
            title: "LBNco Addresses",
            link: "/service/Lbnco_Address",
            component: "CustomReports",
            data: "",
            icon: "fas fa-balance-scale",
          },
          {
            title: "LBNco Site Plans",
            link: "/service/Lbnco_SitePlans",
            component: "CustomReports",
            data: "",
            icon: "fas fa-balance-scale",
          },
          {
            title: "Low Hanging Fruit",
            link: "/service/Opticomm_LowHanging",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Service Lookup",
            link: "/service/Space_History",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "New Activations",
            link: "/service/New_Activations",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Churn Reports",
            link: "/#",
            component: "",
            data: "",
            icon: "fas fa-font",
            Subitems: [
              {
                title: "LBNCo Churn Data",
                link: "/service/Lbnco_Churns",
                component: "CustomReports",
                data: "",
                icon: "fas fa-code-branch",
              },
              {
                title: "OptiComm Churns",
                link: "/service/OptiComm_Churns",
                component: "CustomReports",
                data: "",
                icon: "fas fa-code-branch",
              },
            ],
          },
        ],
      },
      {
        title: "Finance Reports",
        link: "/#",
        component: "",
        data: "",
        icon: "fas fa-font",
        Subitems: [
          {
            title: "Communities Version A",
            link: "/finance/Finance_ReportA",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Communities Version B",
            link: "/finance/Finance_ReportB",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "LBN Promo",
            link: "/finance/Promo_Lbn_A",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "OPC Promo",
            link: "/finance/Promo_Opti_A",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
        ],
      },
      {
        title: "System Reports",
        link: "/#",
        component: "",
        data: "",
        icon: "fas fa-project-diagram",
        Subitems: [
          {
            title: "Joomla RSP Users",
            link: "/system/Joomla_RSPAccounts",
            component: "CustomReports",
            data: "",
            icon: "fas fa-sitemap",
          },
        ],
      },
      {
        title: "Error Reports",
        link: "/#",
        component: "",
        data: "",
        icon: "fas fa-bomb",
        Subitems: [
          {
            title: "ONT Errors",
            link: "/#",
            component: "",
            data: "",
            icon: "fas fa-network-wired",
            Subitems: [
              {
                title: "Invalid Serials",
                link: "/error/Error_InvalidSerial",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Duplicate Serials",
                link: "/errors/Error_DuplicateSerials",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Unverified ONTs",
                link: "/error/Error_UnvalidatedONT",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
            ],
          },
          {
            title: "Service Errors",
            link: "/#",
            component: "",
            data: "",
            icon: "fab fa-servicestack",
            Subitems: [
              {
                title: "Multiple Ports",
                link: "/error/Error_ServiceMultiplePorts",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Multiple ONTs",
                link: "/errors/Error_MultipleONTS",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Service Missing ONT",
                link: "/error/Error_ServiceMissingONT",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
              {
                title: "Service Property No ONT",
                link: "/error/Error_ServiceNotONT",
                component: "CustomReports",
                data: "",
                icon: "fas fa-font",
              },
            ],
          },
          {
            title: "Invalid Properties",
            link: "/commissioning/Opticomm_Invalid_Properties",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "MissMatched ONTS",
            link: "/error/Error_MisMatchedONT",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
        ],
      },
      {
        title: "Space Reports",
        link: "/#",
        component: "",
        data: "",
        icon: "fas fa-font",
        Subitems: [
          {
            title: "LBNco Site RSPs",
            link: "/service/Lbnco_SiteRsps",
            component: "CustomReports",
            data: "",
            icon: "fas fa-balance-scale",
          },
          {
            title: "LBNco RSP Plans",
            link: "/service/Lbnco_RspPlans",
            component: "CustomReports",
            data: "",
            icon: "fas fa-balance-scale",
          },
        ],
      },
      {
        title: "Ticket Reports",
        link: "/#",
        component: "",
        data: "",
        icon: "fas fa-font",
        Subitems: [
          {
            title: "Television Tickets",
            link: "/tickets/Tickets_TeleVision",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
        ],
      },
    ],
  },
  {
    title: "DAD Reports",
    link: "/#",
    component: "",
    data: "",
    icon: "fas fa-server",
    Subitems: [
      {
        title: "ID Lookup",
        link: "/dad/DAD_Lookup",
        component: "CustomReports",
        data: "",
        icon: "fas fa-font",
      },
      {
        title: "History",
        link: "/dad/DAD_History",
        component: "CustomReports",
        data: "",
        icon: "fas fa-font",
      },
      {
        title: "Sync Override",
        link: "/dad/OptiComm_ApproveSync",
        component: "CustomReports",
        data: "",
        icon: "fas fa-font",
      },
    ],
  },
  {
    title: "Dynamics Reports",
    link: "/#",
    component: "",
    data: "",
    icon: "fas fa-candy-cane",
    Subitems: [
      {
        title: "VLANS",
        link: "/dynamics/Dynamics_VLANS",
        component: "CustomReports",
        data: "",
        icon: "fas fa-font",
      },
      {
        title: "RSPS",
        link: "/dynamics/Dynamics_RSPS",
        component: "CustomReports",
        data: "",
        icon: "fas fa-font",
      },
      {
        title: "Exchanges",
        link: "/dynamics/Dynamics_Exchanges",
        component: "CustomReports",
        data: "",
        icon: "fas fa-font",
      },
      {
        title: "OLTS",
        link: "/dynamics/Dynamics_OLTS",
        component: "CustomReports",
        data: "",
        icon: "fas fa-font",
      },
      {
        title: "Communities",
        link: "/dynamics/Dynamics_Communities",
        component: "CustomReports",
        data: "",
        icon: "fas fa-font",
      },
      {
        title: "Order Management",
        link: "/#",
        component: "",
        data: "",
        icon: "fab fa-first-order",
        Subitems: [
          {
            title: "Awaiting Enrichment",
            link: "/dynamics/Dynamics_Orders_Integration",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Engineering Orders",
            link: "/dynamics/Dynamics_Orders_Engineering",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Open Orders",
            link: "/dynamics/Dynamics_Orders_Open",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Order Views",
            link: "/dynamics/Dynamics_Orders",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
        ],
      },
      {
        title: "Middleware Logs",
        link: "/dynamics/Middleware_Orders",
        component: "CustomReports",
        data: "",
        icon: "fas fa-font",
      },
    ],
  },
  {
    title: "Commissioning",
    link: "/#",
    component: "",
    data: "",
    icon: "fas fa-building",
    Subitems: [
      {
        title: "OLT Information",
        link: "/#",
        component: "",
        data: "",
        icon: "fas fa-bolt",
        Subitems: [
          {
            title: "Discovered ONTs",
            link: "/commissioning/OptiComm_DiscoveredOnts",
            component: "CustomReports",
            data: "",
            icon: "fas fa-building",
          },
          {
            title: "Registered ONTs",
            link: "/commissioning/OptiComm_RegisteredOnts",
            component: "CustomReports",
            data: "",
            icon: "fas fa-building",
          },
          {
            title: "Pending ONTs",
            link: "/commissioning/OptiComm_PendingOnts",
            component: "CustomReports",
            data: "",
            icon: "fas fa-building",
          },
          {
            title: "Bulk Logs",
            link: "/commissioning/OptiComm_ONTLogs",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Service Ports",
            link: "/commissioning/Opticomm_ServicePorts",
            component: "CustomReports",
            data: "",
            icon: "fas fa-building",
          },
        ],
      },
      {
        title: "Upload Tools",
        link: "/#",
        component: "",
        data: "",
        icon: "fas fa-upload",
        Subitems: [
          {
            title: "Upload ONTs",
            link: "/design/uploadonts",
            component: "OntUpload",
            data: "",
            icon: "fas fa-font",
          },
        ],
      },
    ],
  },
  {
    title: "Design",
    link: "/#",
    component: "",
    data: "",
    icon: "fas fa-hard-hat",
    Subitems: [
      {
        title: "ONT Register Template",
        link: "/design/OptiComm_ONTRegister",
        component: "CustomReports",
        data: "",
        icon: "fas fa-hard-hat",
      },
      {
        title: "Property Extract",
        link: "/design/OptiComm_PropertyExtract",
        component: "CustomReports",
        data: "",
        icon: "fas fa-hard-hat",
      },
      {
        title: "OptiComm Communities",
        link: "/design/OptiComm_Communities",
        component: "CustomReports",
        data: "",
        icon: "fas fa-hard-hat",
      },
      {
        title: "Upload Tools",
        link: "/#",
        component: "",
        data: "",
        icon: "fas fa-upload",
        Subitems: [
          {
            title: "Property Import",
            link: "/design/uploadproperties",
            component: "OntUpload",
            data: "",
            icon: "fas fa-font",
          },
        ],
      },
    ],
  },
  {
    title: "SuperDAD",
    link: "/super-dad/:table?/:id?",
    component: "SuperDad",
    data: "",
    icon: "fas fa-database",
  },
  {
    title: "LBNco Data Project",
    link: "/#",
    component: "",
    data: "",
    icon: "fas fa-server",
    Subitems: [
      {
        title: "Network Information",
        link: "/#",
        component: "",
        data: "",
        icon: "fas fa-network-wired",
        Subitems: [
          {
            title: "ONT Extract",
            link: "/data/Network_ONTs",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Network Properties",
            link: "/data/Network_Properties",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Service Ports",
            link: "/data/Network_ServicePorts",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Site ONTS",
            link: "/data/Network_Sites",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Network Billing",
            link: "/data/Network_Billing",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
        ],
      },
      {
        title: "System Information",
        link: "/#",
        component: "",
        data: "",
        icon: "far fa-clipboard",
        Subitems: [
          {
            title: "Property Extract",
            link: "/data/Lbnco_Data_Properties",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "Service Address",
            link: "/data/Lbnco_Services_Address",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
          {
            title: "LBNco Master List",
            link: "/data/Lbnco_MasterList",
            component: "CustomReports",
            data: "",
            icon: "fas fa-font",
          },
        ],
      },
    ],
  },
  {
    title: "Customer Tools",
    link: "/#",
    component: "",
    data: "",
    icon: "fab fa-intercom",
    Subitems: [
      {
        title: "Footprint Search",
        link: "/customer/footprint",
        component: "FootPrint",
        data: "",
        icon: "fas fa-font",
      },
      {
        title: "Service Search",
        link: "/customer/services/:service_id?",
        component: "Services",
        data: "",
        icon: "fas fa-font",
      },
      {
        title: "Property Search",
        link: "/customer/properties/:property_id?",
        component: "Properties",
        data: "",
        icon: "fas fa-font",
      },
      {
        title: "Ticket Search",
        link: "/customer/tickets/:ticket_id?",
        component: "Tickets",
        data: "",
        icon: "fas fa-font",
      },
      {
        title: "Ticket Explorer",
        link: "/customer/Ticket_Explorer",
        component: "CustomReports",
        data: "",
        icon: "fas fa-font",
      },
      {
        title: "Order Search",
        link: "/customer/orders/:order_id?",
        component: "Lookup",
        data: "",
        icon: "fas fa-font",
      },
    ],
  },
];

function getPath(model, title) {
  var path,
    item = model.title;

  if (!model || typeof model !== "object") return;

  if (model.title === title) return [item];

  (model.Subitems || []).some((child) => (path = getPath(child, title)));
  return path && [item, ...path];
}

function sliceArrayToTarget(arr, target) {
  return arr.slice(0, arr.indexOf(target));
}

console.log(
  // ***

  //   getPath(MENU_ARR[0], "Menu")
  sliceArrayToTarget(["Admin Tools", "Staff Portal", "Menu"], "Staff Portal")
  // ***
);
