const ACCOUNTS = [
  {
    IsVisible: true,
    DisplayId: "1-0000",
    IsAllowedToMoveDown: false,
    SuggestedChildHeaderDisplayId: "1-1500",
    IsCredit: false,
    Uid: "e0c6483a-042e-4132-8881-c0338f533341",
    SuggestedChildDetailDisplayId: "1-1963",
    AccountType: "Asset",
    IsAllowedToMoveUp: false,
    AccountRecordId: 30,
    IsCurrentEarnings: false,
    IsLinked: false,
    IsRetainedEarnings: false,
    CurrentBalance: -12094,
    Id: 30,
    OpeningBalance: 0,
    IsSystem: true,
    IsHeader: true,
    Level: 1,
    AccountName: "Assets",
    AccountSubType: "OtherAsset",
  },
  {
    IsVisible: true,
    DisplayId: "1-1000",
    IsAllowedToMoveDown: false,
    SuggestedChildHeaderDisplayId: "",
    IsCredit: false,
    Uid: "a5625ac8-77d4-48ab-8b20-b8de22733838",
    SuggestedChildDetailDisplayId: "1-1211",
    AccountType: "Asset",
    IsAllowedToMoveUp: false,
    AccountRecordId: 31,
    IsCurrentEarnings: false,
    ParentAccountId: 30,
    IsLinked: false,
    ParentAccountRecordId: 30,
    IsRetainedEarnings: false,
    CurrentBalance: -12094,
    Id: 31,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: true,
    Level: 2,
    AccountName: "Current Assets",
    AccountSubType: "OtherAsset",
  },
  {
    IsVisible: true,
    DisplayId: "1-1100",
    IsAllowedToMoveDown: false,
    SuggestedChildHeaderDisplayId: "",
    IsCredit: false,
    Uid: "db4fe4de-61dd-4780-b87c-02446af0243d",
    SuggestedChildDetailDisplayId: "1-1161",
    AccountType: "Asset",
    IsAllowedToMoveUp: true,
    AccountRecordId: 32,
    IsCurrentEarnings: false,
    ParentAccountId: 31,
    IsLinked: false,
    ParentAccountRecordId: 31,
    IsRetainedEarnings: false,
    CurrentBalance: -12394,
    Id: 32,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: true,
    Level: 3,
    AccountName: "Bank Accounts",
    AccountSubType: "OtherAsset",
  },
  {
    TaxCodeId: 4,
    IsVisible: true,
    TaxCode: "N-T",
    DisplayId: "1-1110",
    IsAllowedToMoveDown: false,
    IsCredit: false,
    Uid: "1c5c0f3f-dc9a-45b5-a570-2797ab1482b7",
    AccountType: "Asset",
    IsAllowedToMoveUp: true,
    AccountRecordId: 33,
    IsCurrentEarnings: true,
    ParentAccountId: 32,
    IsLinked: true,
    ParentAccountRecordId: 32,
    IsRetainedEarnings: true,
    CurrentBalance: 10895.09,
    Id: 33,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: false,
    Level: 4,
    AccountName: "Business Bank Account #1",
    AccountSubType: "Bank",
  },
  {
    TaxCodeId: 4,
    IsVisible: true,
    TaxCode: "N-T",
    DisplayId: "1-1160",
    IsAllowedToMoveDown: false,
    IsCredit: false,
    Uid: "a2b79ee7-9abd-434e-8550-68aa9bb2cb03",
    AccountType: "Asset",
    IsAllowedToMoveUp: true,
    AccountRecordId: 34,
    IsCurrentEarnings: false,
    ParentAccountId: 32,
    IsLinked: false,
    ParentAccountRecordId: 32,
    IsRetainedEarnings: false,
    CurrentBalance: -23289.09,
    Id: 34,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: false,
    Level: 4,
    AccountName: "Petty Cash",
    AccountSubType: "Bank",
  },
  {
    TaxCodeId: 4,
    IsVisible: true,
    TaxCode: "N-T",
    DisplayId: "1-1170",
    IsAllowedToMoveDown: true,
    IsCredit: false,
    Uid: "9dbcc402-b291-44cf-8cb6-199db3a89742",
    AccountType: "Asset",
    IsAllowedToMoveUp: true,
    AccountRecordId: 35,
    IsCurrentEarnings: true,
    ParentAccountId: 31,
    IsLinked: true,
    ParentAccountRecordId: 31,
    IsRetainedEarnings: true,
    CurrentBalance: 300,
    Id: 35,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: false,
    Level: 3,
    AccountName: "Undeposited Funds Account",
    AccountSubType: "Bank",
  },
  {
    TaxCodeId: 4,
    IsVisible: true,
    TaxCode: "N-T",
    DisplayId: "1-1171",
    IsAllowedToMoveDown: false,
    IsCredit: false,
    Uid: "9516f0f8-2bdc-44a2-ad80-d5a148bd5191",
    AccountType: "Asset",
    IsAllowedToMoveUp: true,
    AccountRecordId: 36,
    IsCurrentEarnings: true,
    ParentAccountId: 31,
    IsLinked: true,
    ParentAccountRecordId: 31,
    IsRetainedEarnings: true,
    CurrentBalance: 0,
    Id: 36,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: false,
    Level: 3,
    AccountName: "Electronic Clearing Account",
    AccountSubType: "Bank",
  },
  {
    TaxCodeId: 4,
    IsVisible: true,
    TaxCode: "N-T",
    DisplayId: "1-1200",
    IsAllowedToMoveDown: false,
    IsCredit: false,
    Uid: "b7e2daaf-761e-4370-912b-dd2aed19712f",
    AccountType: "Asset",
    IsAllowedToMoveUp: true,
    AccountRecordId: 37,
    IsCurrentEarnings: true,
    ParentAccountId: 31,
    IsLinked: true,
    ParentAccountRecordId: 31,
    IsRetainedEarnings: true,
    CurrentBalance: 0,
    Id: 37,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: false,
    Level: 3,
    AccountName: "Accounts Receivable",
    AccountSubType: "AccountReceivable",
  },
  {
    TaxCodeId: 4,
    IsVisible: true,
    TaxCode: "N-T",
    DisplayId: "1-1210",
    IsAllowedToMoveDown: false,
    IsCredit: false,
    Uid: "c84c0d09-772f-477a-9315-29411205f9ba",
    AccountType: "Asset",
    IsAllowedToMoveUp: true,
    AccountRecordId: 38,
    IsCurrentEarnings: false,
    ParentAccountId: 31,
    IsLinked: false,
    ParentAccountRecordId: 31,
    IsRetainedEarnings: false,
    CurrentBalance: 0,
    Id: 38,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: false,
    Level: 3,
    AccountName: "Other Receivables",
    AccountSubType: "AccountReceivable",
  },
  {
    TaxCodeId: 4,
    IsVisible: true,
    TaxCode: "N-T",
    DisplayId: "1-1962",
    IsAllowedToMoveDown: false,
    IsCredit: false,
    Uid: "1a60809e-41f6-440c-9d8d-686fbe637b55",
    AccountType: "Asset",
    IsAllowedToMoveUp: true,
    AccountRecordId: 39,
    IsCurrentEarnings: true,
    ParentAccountId: 30,
    IsLinked: true,
    ParentAccountRecordId: 30,
    IsRetainedEarnings: true,
    CurrentBalance: 0,
    Id: 39,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: false,
    Level: 3,
    AccountName: "Deposits To Suppliers",
    AccountSubType: "OtherCurrentAsset",
  },
  {
    IsVisible: true,
    DisplayId: "1-2100",
    IsAllowedToMoveDown: false,
    SuggestedChildHeaderDisplayId: "",
    IsCredit: false,
    Uid: "c0794632-e77e-4c63-a934-a869b7902dcc",
    SuggestedChildDetailDisplayId: "1-2521",
    AccountType: "Asset",
    IsAllowedToMoveUp: true,
    AccountRecordId: 40,
    IsCurrentEarnings: false,
    ParentAccountId: 30,
    IsLinked: false,
    ParentAccountRecordId: 30,
    IsRetainedEarnings: false,
    CurrentBalance: 0,
    Id: 40,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: true,
    Level: 3,
    AccountName: "Property, Plant & Equipment",
    AccountSubType: "FixedAsset",
  },
  {
    TaxCodeId: 3,
    IsVisible: true,
    TaxCode: "CAP",
    DisplayId: "1-2110",
    IsAllowedToMoveDown: false,
    IsCredit: false,
    Uid: "d8376f92-b23d-4c2e-ad09-07f315e7b83c",
    AccountType: "Asset",
    IsAllowedToMoveUp: true,
    AccountRecordId: 41,
    IsCurrentEarnings: false,
    ParentAccountId: 40,
    IsLinked: false,
    ParentAccountRecordId: 40,
    IsRetainedEarnings: false,
    CurrentBalance: 0,
    Id: 41,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: false,
    Level: 4,
    AccountName: "Plant & Equipment",
    AccountSubType: "FixedAsset",
  },
  {
    TaxCodeId: 4,
    IsVisible: true,
    TaxCode: "N-T",
    DisplayId: "1-2120",
    IsAllowedToMoveDown: false,
    IsCredit: false,
    Uid: "9637db21-06b8-412d-91f5-e42a33095ee4",
    AccountType: "Asset",
    IsAllowedToMoveUp: true,
    AccountRecordId: 42,
    IsCurrentEarnings: false,
    ParentAccountId: 40,
    IsLinked: false,
    ParentAccountRecordId: 40,
    IsRetainedEarnings: false,
    CurrentBalance: 0,
    Id: 42,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: false,
    Level: 4,
    AccountName: "Accum. Depr. Plant & Equipment",
    AccountSubType: "FixedAsset",
  },
  {
    TaxCodeId: 3,
    IsVisible: true,
    TaxCode: "CAP",
    DisplayId: "1-2510",
    IsAllowedToMoveDown: false,
    IsCredit: false,
    Uid: "efb0f649-9a1f-43b8-922f-7af2b8ca95fe",
    AccountType: "Asset",
    IsAllowedToMoveUp: true,
    AccountRecordId: 43,
    IsCurrentEarnings: false,
    ParentAccountId: 40,
    IsLinked: false,
    ParentAccountRecordId: 40,
    IsRetainedEarnings: false,
    CurrentBalance: 0,
    Id: 43,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: false,
    Level: 4,
    AccountName: "Motor Vehicles",
    AccountSubType: "FixedAsset",
  },
  {
    TaxCodeId: 4,
    IsVisible: true,
    TaxCode: "N-T",
    DisplayId: "1-2520",
    IsAllowedToMoveDown: false,
    IsCredit: false,
    Uid: "3e1c715a-325a-4780-b9df-3cc62b2d142c",
    AccountType: "Asset",
    IsAllowedToMoveUp: true,
    AccountRecordId: 44,
    IsCurrentEarnings: false,
    ParentAccountId: 40,
    IsLinked: false,
    ParentAccountRecordId: 40,
    IsRetainedEarnings: false,
    CurrentBalance: 0,
    Id: 44,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: false,
    Level: 4,
    AccountName: "Accum. Depr Motor Vehicles",
    AccountSubType: "FixedAsset",
  },
  {
    IsVisible: true,
    DisplayId: "2-0000",
    IsAllowedToMoveDown: false,
    SuggestedChildHeaderDisplayId: "2-1000",
    IsCredit: true,
    Uid: "3161151b-dd63-427c-8aad-3bb4345b8859",
    SuggestedChildDetailDisplayId: "2-2501",
    AccountType: "Liability",
    IsAllowedToMoveUp: false,
    AccountRecordId: 45,
    IsCurrentEarnings: false,
    IsLinked: false,
    IsRetainedEarnings: false,
    CurrentBalance: -1099.44,
    Id: 45,
    OpeningBalance: 0,
    IsSystem: true,
    IsHeader: true,
    Level: 1,
    AccountName: "Liabilities",
    AccountSubType: "OtherLiability",
  },
  {
    IsVisible: true,
    DisplayId: "2-0010",
    IsAllowedToMoveDown: false,
    SuggestedChildHeaderDisplayId: "2-1300",
    IsCredit: true,
    Uid: "d9c32a33-d298-4ddb-8b0c-22c2cd3cb36d",
    SuggestedChildDetailDisplayId: "2-1555",
    AccountType: "Liability",
    IsAllowedToMoveUp: false,
    AccountRecordId: 46,
    IsCurrentEarnings: false,
    ParentAccountId: 45,
    IsLinked: false,
    ParentAccountRecordId: 45,
    IsRetainedEarnings: false,
    CurrentBalance: -1099.44,
    Id: 46,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: true,
    Level: 2,
    AccountName: "Current Liabilities",
    AccountSubType: "OtherCurrentLiability",
  },
  {
    IsVisible: true,
    DisplayId: "2-1100",
    IsAllowedToMoveDown: false,
    SuggestedChildHeaderDisplayId: "",
    IsCredit: true,
    Uid: "9d4873f0-d3e0-4bea-ba75-f3659e804f1f",
    SuggestedChildDetailDisplayId: "2-1111",
    AccountType: "Liability",
    IsAllowedToMoveUp: true,
    AccountRecordId: 47,
    IsCurrentEarnings: false,
    ParentAccountId: 46,
    IsLinked: false,
    ParentAccountRecordId: 46,
    IsRetainedEarnings: false,
    CurrentBalance: 0,
    Id: 47,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: true,
    Level: 3,
    AccountName: "Credit Cards",
    AccountSubType: "OtherCurrentLiability",
  },
  {
    TaxCodeId: 4,
    IsVisible: true,
    TaxCode: "N-T",
    DisplayId: "2-1110",
    IsAllowedToMoveDown: false,
    IsCredit: true,
    Uid: "4c74ad80-60c8-467b-be90-f973ac004859",
    AccountType: "Liability",
    IsAllowedToMoveUp: true,
    AccountRecordId: 48,
    IsCurrentEarnings: false,
    ParentAccountId: 47,
    IsLinked: false,
    ParentAccountRecordId: 47,
    IsRetainedEarnings: false,
    CurrentBalance: 0,
    Id: 48,
    OpeningBalance: 0,
    IsSystem: false,
    IsHeader: false,
    Level: 4,
    AccountName: "Credit Card #1",
    AccountSubType: "CreditCard",
  },
];

const getAccountNameById = (accountsList, id) => {
  const found = accountsList.find((account) => account.Id === id);
  // return found;
  return found && found.AccountName;
};

console.log(
  // ****
  getAccountNameById(ACCOUNTS, 54548)
  // ****
);
